---
title: "Usage"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Usage}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Load packages

```{r setup}
library(iSEE)
library(iSEEClusterProfiler)
```

# Example data

```{r}
library(scRNAseq)

# Example data ----
sce <- ReprocessedAllenData(assays="tophat_counts")
class(sce)

library(scater)
sce <- logNormCounts(sce, exprs_values="tophat_counts")

sce <- runPCA(sce, ncomponents=4)
sce <- runTSNE(sce)
rowData(sce)$ave_count <- rowMeans(assay(sce, "tophat_counts"))
rowData(sce)$n_cells <- rowSums(assay(sce, "tophat_counts") > 0)
sce
```
# Set global options

```{r}
iSEEOptions$set(
  orgdb.package = "org.Mm.eg.db",
  orgdb.key = NA_character_,      # use rownames 
  orgdb.keytype = "SYMBOL"
)
str(iSEEOptions$get())
```

# Configure and launch the app

```{r}
initial <- list(
  ClusterProfilerTable(
    RowSelectionSource = "RowDataPlot1", PanelWidth = 8L
  ),
  RowDataPlot()
)
app <- iSEE(sce, initial = initial)
```
